name: Firebase Deploy

on:
  push:
    branches: 
    - main

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: Web Ui
    steps:
      - uses: actions/checkout@v3
      - run: npm ci
      - run: npm run build
      - name: GitHub Action for Firebase
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}