name: Firebase Deploy
on:
  push:
    branches: 
    - main
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: Web Ui
    steps:
      - uses: actions/checkout@v3

      - name: Install Dependencies
        run: npm install

      - name: Creating .env file
        run: |
          echo REACT_APP_BACKEND_URL=${{ secrets.REACT_APP_BACKEND_URL }} >> ./.env

      - uses: actions/setup-node@v1
      - run: npm ci
      - run: npm run build

      - name: GitHub Action for Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}